// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MathService.proto

/*
Package MathService is a generated protocol buffer package.

It is generated from these files:
	MathService.proto

It has these top-level messages:
	AddRequest
	AddReply
	Person
	AddressBook
*/
package MathService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type AddRequest struct {
	A int32 `protobuf:"varint,1,opt,name=A" json:"A,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=B" json:"B,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddReply struct {
	X int32 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
}

func (m *AddReply) Reset()                    { *m = AddReply{} }
func (m *AddReply) String() string            { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()               {}
func (*AddReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

type Person struct {
	Name   []byte                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id     int32                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email  string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Person) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "AddRequest")
	proto.RegisterType((*AddReply)(nil), "AddReply")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "AddressBook")
	proto.RegisterEnum("Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MathService service

type MathServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
}

type mathServiceClient struct {
	cc *grpc.ClientConn
}

func NewMathServiceClient(cc *grpc.ClientConn) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := grpc.Invoke(ctx, "/MathService/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MathService service

type MathServiceServer interface {
	Add(context.Context, *AddRequest) (*AddReply, error)
}

func RegisterMathServiceServer(s *grpc.Server, srv MathServiceServer) {
	s.RegisterService(&_MathService_serviceDesc, srv)
}

func _MathService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MathService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MathService.proto",
}

func init() { proto.RegisterFile("MathService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x51, 0x5d, 0x6b, 0xc2, 0x30,
	0x14, 0x35, 0xb5, 0x76, 0xf6, 0x56, 0x44, 0xef, 0xc6, 0x28, 0xbe, 0x28, 0x85, 0x41, 0x41, 0xc8,
	0x83, 0xfb, 0x05, 0x2d, 0x08, 0x1b, 0xd3, 0x29, 0xd9, 0x60, 0xbe, 0xea, 0x72, 0xc1, 0x32, 0x6d,
	0xb2, 0xb6, 0x0e, 0xfc, 0xcb, 0xfb, 0x15, 0x23, 0xb1, 0x6e, 0xee, 0xed, 0x9e, 0x0f, 0xce, 0x69,
	0x4f, 0xa0, 0x3f, 0x5f, 0x57, 0xdb, 0x17, 0x2a, 0xbe, 0xb2, 0x77, 0xe2, 0xba, 0x50, 0x95, 0x8a,
	0x62, 0x80, 0x44, 0x4a, 0x41, 0x9f, 0x07, 0x2a, 0x2b, 0xec, 0x00, 0x4b, 0x42, 0x36, 0x62, 0x71,
	0x4b, 0xb0, 0xc4, 0xa0, 0x34, 0x74, 0x4e, 0x28, 0x8d, 0x42, 0x68, 0x5b, 0xa7, 0xde, 0x1d, 0x8d,
	0xb2, 0x3a, 0xfb, 0x56, 0xd1, 0x37, 0x03, 0x6f, 0x49, 0x45, 0xa9, 0x72, 0x44, 0x70, 0xf3, 0xf5,
	0x9e, 0xac, 0xd6, 0x11, 0xf6, 0xc6, 0x2e, 0x38, 0x99, 0xac, 0x73, 0x9c, 0x4c, 0xe2, 0x0d, 0xb4,
	0x68, 0xbf, 0xce, 0x76, 0x61, 0x73, 0xc4, 0x62, 0x5f, 0x9c, 0x00, 0x8e, 0xc1, 0xd3, 0x5b, 0x95,
	0x53, 0x19, 0xba, 0xa3, 0x66, 0x1c, 0x4c, 0xae, 0xf9, 0x29, 0x92, 0x2f, 0x0d, 0xfb, 0x7c, 0xd8,
	0x6f, 0xa8, 0x10, 0xb5, 0x65, 0x30, 0x83, 0xe0, 0x82, 0xc6, 0x5b, 0xf0, 0x72, 0x7b, 0xd9, 0x5e,
	0x5f, 0xd4, 0x08, 0xef, 0xc0, 0xad, 0x8e, 0x9a, 0x6c, 0x77, 0x77, 0xd2, 0xff, 0x97, 0xf8, 0x7a,
	0xd4, 0x24, 0xac, 0x1c, 0x8d, 0xc1, 0xff, 0xa5, 0x10, 0xc0, 0x9b, 0x2f, 0xd2, 0xc7, 0xd9, 0xb4,
	0xd7, 0xc0, 0x36, 0xb8, 0x0f, 0x8b, 0xf9, 0xb4, 0xc7, 0xcc, 0xf5, 0xb6, 0x10, 0x4f, 0x3d, 0x27,
	0xe2, 0x10, 0x24, 0x52, 0x16, 0x54, 0x96, 0xa9, 0x52, 0x1f, 0x38, 0x04, 0x4f, 0x93, 0xd2, 0x3b,
	0xf3, 0xcb, 0xe6, 0xb3, 0xaf, 0xea, 0x12, 0x51, 0xd3, 0x13, 0x0e, 0xc1, 0xc5, 0xea, 0x38, 0x84,
	0x66, 0x22, 0x25, 0x06, 0xfc, 0x6f, 0xf5, 0x81, 0xcf, 0xcf, 0xc3, 0x46, 0x8d, 0x8d, 0x67, 0xdf,
	0xe5, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x23, 0x29, 0x81, 0xac, 0x01, 0x00, 0x00,
}
